### PR TITLE
Added a January-centred mean output

### PR DESCRIPTION
**Pull request by mrghg**
For use in E.g. the model used by Chapter 7 of the Ozone Assessment

### CODE REVIEW

**Comment by lukewestern** [comment]
Do they only need mf to be Jan centred? i.e., not emissions?

Also, nowhere in the output do we have a definition of the boxes (just names box0, box1 etc).
Should we add an auxiliary file to the outputs, or in the comment string?

**Comment by mrghg** [comment]
I think it's just mole fraction.

Good point about the boxes. I think we should add some info in the comment string.

**Comment by lukewestern** [comment]
I've added a little table to the comment string for the box descriptions. Not sure if it's a bit much for a comment, but describes all boxes.

**Comment by mrghg** [comment]
Ooh, lovely!

**Review by lukewestern — APPROVED** [review]
OK, think we're all good then.

**Pull request merged**
